sudo: false

language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "4"
  - "5"
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install -g grunt-cli
  - npm install

script:
  - npm run test
