export const UPDATE_PRODUCT_LIST = "UPDATE_PRODUCT_LIST";
export const UPDATE_PRODUCT_ID = "UPDATE_PRODUCT_ID";
export const UPDATE_PRODUCT_NAME = "UPDATE_PRODUCT_NAME";

export const UPDATE_ROUND_LIST = "UPDATE_ROUND_LIST";
export const UPDATE_ROUND_ID = "UPDATE_ROUND_ID";
export const UPDATE_ROUND_NAME = "UPDATE_ROUND_NAME";

export const UPDATE_ZONE_LIST = "UPDATE_ZONE_LIST";
export const UPDATE_ZONE_ID = "UPDATE_ZONE_ID";
export const UPDATE_ZONE_NAME = "UPDATE_ZONE_NAME";

export const UPDATE_DATE = "UPDATE_DATE";
export const UPDATE_SEAT_SELECTED_LIST = "UPDATE_SEAT_SELECTED_LIST";


export const UPDATE_VENUE_ID = "UPDATE_VENUE_ID";
export const UPDATE_VENUE_NAME = "UPDATE_VENUE_NAME";

export const UPDATE_SELECTED_LIST = "UPDATE_SELECTED_LIST"
